### ISSUE TITLE
关于Linux

### ISSUE THREAD

**Issue by moyanj** [vikiboss/gs-helper#3]
请问该英语释放可以于Linux下使用，如果可以该如何编译

**Comment by vikiboss** [comment]
首先这个项目已经不再维护了，需要登录的功能基本不能用了，如果你是想使用相关功能，可能这个项目已经不适合你了，也有两年多了，技术栈可能也有些落后了。

其次，这个项目已经配置了三个主流平台的打包配置（Linux、Windows、macOS），参考：https://github.com/vikiboss/gs-helper/blob/309c53f8155a7e8f03030f57645fc60508dddbac/forge.config.js#L10

只要在对应平台执行构建脚本就行，详情查看 package.json 的 make 命令。

但是跨平台会有交叉编译的问题，也就是说无法在 Windows 环境构建 Linux 的安装包，所以你需要一个 Linux 环境进行编译。
